name: Deploy Frontend to Scaleway

on:
  push:
    branches: [main]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Scaleway Container Registry
        run: echo "${{ secrets.SCW_SECRET_KEY }}" | docker login rg.fr-par.scw.cloud/namespace-botros-john -u nologin --password-stdin

      - name: Build and push frontend
        run: |
          docker build -f ./front/DockerFile -t rg.fr-par.scw.cloud/namespace-botros-john/front:latest front
          docker push rg.fr-par.scw.cloud/namespace-botros-john/front:latest
